CREATE TABLE BORROWER(
	AUTOID INT IDENTITY(1,1) NOT NULL,
	BORROWER_ID AS 'R' + RIGHT(('00' + CONVERT(VARCHAR,AUTOID)),2) PERSISTED NOT NULL primary key,
	[FIRSTNAME] nvarchar(50),
	[LASTNAME] nvarchar(50),
	[ADDRESS] nvarchar(225),
	[PHONE] VARCHAR(10)					NOT NULL,

	 CONSTRAINT MANAGER_PHONE_Format CHECK (LEN(PHONE) = 10 AND PHONE LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
)
GO

CREATE TABLE BOOK(
	AUTOID INT IDENTITY(1,1) NOT NULL,
	BOOK_ID AS 'B' + RIGHT(('00' + CONVERT(VARCHAR,AUTOID)),2) PERSISTED NOT NULL primary key,
	BOOKNAME nvarchar(50),
	AUTHOR nvarchar(50),
	PUBLICATION_YEAR int
)
GO

CREATE TABLE BORROW(
	BORROWER_ID varchar(3) not null,
	BOOK_ID varchar(3) not null,
	BORROWED_DATE datetime not null,
	RETURN_DATE datetime default null,

	primary key (BORROWER_ID, BOOK_ID, BORROWED_DATE),
	FOREIGN KEY(BOOK_ID) REFERENCES BOOK(BOOK_ID),
	FOREIGN KEY(BORROWER_ID) REFERENCES BORROWER(BORROWER_ID),
)
GO

--DROP TABLE BORROW;
--DROP TABLE BOOK;
--DROP TABLE BORROWER;

INSERT INTO BORROWER
VALUES('THUY DUONG', 'NGUYEN', '21 LE DAI, DANANG, VIETNAM','0123456654')
INSERT INTO BORROWER
VALUES('VAN NGUYEN', 'NGUYEN', '25 NGUYEN DU, HUE, VIETNAM','0123456789')
INSERT INTO BORROWER
VALUES('QUANG THANG', 'NGO', '21 CO GIANG, DANANG, VIETNAM','0987654321')
INSERT INTO BORROWER
VALUES('THI LAN', 'NGUYEN', '30 LE HUU TRAC, DANANG, VIETNAM','0123312456')

INSERT INTO BOOK
VALUES('C# 6.0 AND TH .NET 4.6', 'ANDREW TROELSEN','2015')
INSERT INTO BOOK
VALUES('C# PROGRAMING YELLOW BOOK', 'NULLROB MILES','2016')
INSERT INTO BOOK
VALUES('CARE JAVA VOLUME - FUNDAMENTAL', 'CAY S. HORSTMANN','2018')
INSERT INTO BOOK
VALUES('EFFECTIVE JAVA', 'JOSHUA BLOCH','2017')
INSERT INTO BOOK
VALUES('THE BASICS OF DATABASE', 'VIJI KUMAR','2017')

INSERT INTO BORROW
VALUES('R01', 'B01','2021-06-28','2021-06-30')
INSERT INTO BORROW
VALUES('R01', 'B02','2021-07-01', null)
INSERT INTO BORROW
VALUES('R02', 'B01','2021-07-03', null)
INSERT INTO BORROW
VALUES('R03', 'B03','2021-07-08', null)
INSERT INTO BORROW
VALUES('R03', 'B04','2021-07-03', null)